---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    JOBS: 1
    secure: fOTO/HpUT0xsfml9iXuEL9qBu0NVErcig6CmrS1DFv7f4x9/mYQMNzLUv5b6VBPqGHeFNHiGaUUza3Ufc5KpL7DOu/1y6TFQlSoM6MRRdIXb+50MObvkJ4wXwYJH7Zrb4g8RTaBOY9uU5XQkm/E6GWWF3NiYFoVzCYPNSgAALko1caoEX2hoJNXJSd0T4G+gxtxc2g08RGunBPLqIyy2avMRN4yq0WDN2NbBrztM01FA5RoOLPyX0hhzyIZ+45z34wKvZtu7rj9h1KbFOZOVFJWpHDa0bXxhF63ldxPINe2QMOSsOD22Czk1+IKyC+88gtkvUq7pGUaJK6YdVDRcW9G/DMHVy/IE2aFabrPDVgzrmeCoVKzATzt8nMfIMTTu9Unoa5fdohpJ0NPhYnPfVAGfJ+2MPITgP+x2X6M5+KgHCBdaIgwBVnZE9DTb1L9c/Eh50zeHHbfv9L+NVlbQFzMWNj+kKWMj0qwh6JPpSFiKaOvTK6XP+NSUc7euAZgqK6lwqS07pvcql4qvzbeRWyn/GZuRHOGvfkUNuvLee8dMKfpF3s1VQ6blHHqKB8qH2ifxawiztWgUkYxK0GFTk//ZopLzP90bLl0JiGlg517tp5V9eBOK5ZlPwsSOhD+wta9gCssPjK4i2H2IwLox7AqXegigBMdqIbXz9LaFVAY=

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/
    # greenkeeper branches
    - /^greenkeeper\/.*$/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - COVERAGE=true yarn test
        - codecov

    # - name: "Floating Dependencies"
    #   script:
    #     - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codecov

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    rooms:
      secure: jFWUct9LaaJDHcMS3UwfYH112QGKhi0t8i3saK6SUTbgNIe1UQB7s+YbvlG3gG/a/fwpTK0TSCGv8CIykuqeAvi1NsZHyKhlg/zE5B6/wBlEn5LfAz9hA7tLmFwlGopL8/xAleo7jPIpdbSotprCHjFhDPysRtEa3oIyzJlpYOreQJ0GR+8D4vw2IJLSI+Kczqbu+cEApmtPE4WBgdmLl8ZO8mNgawE5vNry5+gnS2DUUMg3RRkGepjyaCPCDISCqpllaSMZRaLsxaRBPeDsdakLK5HHB0CwxbXg1ZYYqqgghvB56AZvJ4lU6C0hc1Lv8uhzxAKzgGHAllgmLymTia/f41AxyvyBuyGGV9IHytziF0plYJBTneDJ2NLrLDsPefM0MBwgmXRJaH5yVW124vRy9ZHNEed6TGPmO3LGT6alIgpoc/dFsP988/8Qi6nVbyiXNlaY8D1ofVgJ1J3IBgnNCvCBc+k0H0+yfNS7JDV2830WC40E4yHAJXEnPGLtDUc8Tz722c0mXBe6st8CBhGtvt+3Bf7K8ZiIDgcbM6ePzleJ/pLPlXpTFjXRev/DcipKAjzxjk7c/8pRiq2s+k22rxgp5FNZe98ayP8XxO4EGxKaC2ZAplCdLx3HtR+P+fYSypW6WNOZZznD5JVPbx7iE6AwZ32beImXbp9l7Rg=

deploy:
  provider: npm
  skip_cleanup: true
  email: devo.tox.89@gmail.com
  api_key:
    secure: ExZ7ghkLjtpp//s8Vcs/tVYSlsTvZgu4g24elJfzuqmHd3Z1RZaueW36XurNdVRUijpaJw40Swj+8UfnV4ERIFlPQMODjsdWp/Z1lKdwCihCJqXbsWnpoTZ1jxDfIIoyHotCkogcGEdqHEW+7CE/bqqq52ohYuy4dzWud0Tgjtemq7+hp4jFZAdNgQuHhAwSfRRkMjO3HW+gVvKdPhv9qzwRHZ4YlI65k+4FOPPmNJGb4MpN5sPnCoT/RyWgxM2R767WfSGAI4G1gkPQbk46nDG9/P1H7U6iyT97TjkybpkWhnTJnu8xv9joFsPiYskMckJ1kcFTyUZH/7OkN5dxlA0gFOGlTXVrqK2BcsPW9DNlnNNHLFYIOMJmTcRxIWAnDtXXO89T4X66FtNfilfmg0JOQMR5XVJHzLGT+Q+RuPjYqTv0NMKIMhn8CIID17vsrZCS84eY0pkU2rOLGwSWAEf0LyPhkdu8R8zUefxYBAGCBXDHJ7OhJXG0D5/X7gywaXkr1bSPN3EFZm9UCHdhnjhqeYTa1UH90bX6Cum1USoEuToAt4dTuhE4VEs3Kt2DaaNmsTs3Lho4R9JkDLx7NmfeNJMHWHs6/xlkZHJqhrwDTU94/ZfOQBL2+yQEfKwZkEuScRdN1lZ/oHm7+oqu4H/zeXPj6R9qETCXii3gksE=
  on:
    tags: true
    repo: devotox/ember-simple-auth-firebase
